# Generated by Django 2.1.5 on 2023-08-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('j_description', models.CharField(max_length=1000, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('offer', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Juser')),
            ],
        ),
    ]
