# Generated by Django 2.1.5 on 2023-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_of_opening',
            field=models.IntegerField(default=1),
        ),
    ]
